name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.docker_build.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: onyeechris/post-backend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: main-${{ github.sha }}

      - name: Set output image tag
        id: set_output
        run: echo "::set-output name=image_tag::main-${{ github.sha }}"


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kube_config
        run: aws eks update-kubeconfig --name demony-cluster --region us-east-1

      - name: Set IMAGE_TAG environment variable
        run: echo "IMAGE_TAG=main-${{ github.sha }}" >> $GITHUB_ENV
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"
          id: install

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"
        id: install

      #- name: Configure AWS Credentials
       # uses: aws-actions/configure-aws-credentials@v4
        #with:
         # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: us-east-1

      #- name: Update kube_config
       # run: |
        #  aws eks update-kubeconfig --name cluster-demon --region us-east-1 || exit 1

      - name: Deploy to Kubernetes
        run: kubectl apply -f mongodb.yml
      
      - name: Wait for 120 seconds before deploying backend
        run: sleep 120

      - name: Replace image tag in deployment file
        run: sed -i 's|onyeechris/post-backend:latest|onyeechris/post-backend:${{ env.IMAGE_TAG }}|' backend.yml
        
      - name: Deploy to Kubernetes
        run: kubectl apply -f backend.yml
